name: Python package

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
            - name: Install dependencies
              run: |
                  sudo apt -y install libgeos-dev
                  python -m pip install --upgrade pip
                  pip install tox
            - name: Run tox
              run: |
                  tox
